class Insult
  def initialize(options={})
    
  end
  
  ISN1 = [
    "Your mouth spews",
    "You are",
    "Your mother wears",
    "Your Village Priest is",
    "Your Eleventh Child will be",
    "Your Maternal Ancestors are",
    "Your Personal Trainer is",
    "Your spouse thinks you are",
    "Your mind resembles",
    "Your chances for the future are",
    "Your mother-in-law loves",
    "Your closest friend is",
    "Your breath resembles",
    "Your right nostril is dripping",
    "Your politics are",
    "Your cherished desires are",
    "Your next meal should be",
    "Your bedroom resembles",
    "Your refrigerator smells like",
    "Your manners are no better than",
    "I saw you eating and enjoying",
    "Next Friday you will consume",
    "May you wallow in",
    "May you swim in",
    "May you drown in",
    "May you take simple pleasure in",
    "May you find your hot tub filled with",
    "May you find your kitchen sink overflowing with",
    "May you be immersed in",
    "You secretly aspire to drink",
    "May you dine often on",
    "May you be caught dining on",
    "May you become an obsessive collector of",
    "May you find your car filled with",
    "May you blurt out that your boss is the",
    "Your garden should be flooded with",
    "May your basement overflow with",
    "May your underwear be filled with",
    "May your drawers be filled with",
    "May you float forever in",
    "May your feet be encased in",
    "May you be forever entombed in",
    "I hate to tell you, but there, caught in your teeth is",
    "May you step in",
    "May your captors feed you on",
    "The talk around the office is that you eat",
    "May your private parts be encrusted with",
    "May the stains on your clothing be only",
    "May your porridge be infused with",
    "Your sock drawer is now filled with",
    "Your supervisor secretly saves",
    "Caution: Someone knows about your foot fetish",
    "May you die of",
    "Remember that day you first tasted",
    "May all your wastebaskets suddently overflow with",
    "May your roof drip",
    "May you be without garlic to spice your meal of ",
    "May your trough be filled with",
    "May your hip pockets overflow with",
    "May your doctor prescribe",
    "May you trip and fall into",
    "Yeah? Well, your Mentor wears combat boots filled with",
    "So what if I like anchovies and",
    "You relish",
    "I'm going to tell.  You play with",
    "Your body reeks of",
    "May your in-basket overflow with",
    "May your inlaws learn of your fondness for",
    "May you smear yourself with",
    "Your wish is granted: drink",
    "Everyone knows you bathe in"
  ]

  ISN2 = [
    "aniline",
    "virescent",
    "aquamarine",
    "ashy",
    "atramentous",
    "aureate",
    "bloody",
    "bluish",
    "brinded",
    "bronze",
    "cadaverous",
    "cadmium",
    "carmine",
    "carnadine",
    "carroty",
    "cerulean",
    "citrine",
    "cloudy",
    "cochineal",
    "crimson",
    "crude",
    "cyanic",
    "cymophanous",
    "dappled",
    "diaphanous",
    "dingy",
    "drab",
    "dun",
    "emerald",
    "erubescent",
    "fallow",
    "flashy",
    "flavous",
    "florid",
    "florid",
    "foggy",
    "fulvid",
    "fulvous",
    "fuscous",
    "garish",
    "gaudy",
    "gauzy",
    "ghastly",
    "glaucous",
    "gray",
    "greenish",
    "harlequin",
    "hueless",
    "impervious",
    "infuscated",
    "iridescent",
    "jaundiced",
    "khaki",
    "lack-luster",
    "lavender",
    "leaden",
    "limpid",
    "liver-colored",
    "lurid",
    "luteous",
    "mantled",
    "maroon",
    "matted",
    "milky",
    "misty",
    "misty",
    "motley",
    "mottled",
    "ocherous",
    "opacous",
    "opaline",
    "orangish",
    "pallid",
    "pallorous",
    "pellucid",
    "piebald",
    "polychromatic",
    "porraceous",
    "puce",
    "purplish",
    "red",
    "roseate",
    "rouged",
    "rubicund",
    "ruddy",
    "russet",
    "rusty",
    "rusty",
    "sallow",
    "sacharine",
    "scarlet",
    "shady",
    "skewbald",
    "smalty",
    "smoky",
    "yellowish",
    "somber",
    "striated",
    "tallowy"
  ]

  ISN3 = [
    "abomination",
    "soilure",
    "abscess",
    "averruncation",
    "belch",
    "carbuncle",
    "caries",
    "carrion",
    "catamenia",
    "cesspool",
    "cheese-parings",
    "coarseness",
    "compost",
    "contaminate",
    "contamination",
    "coprolite",
    "corruption",
    "dandruff",
    "decay",
    "defedation",
    "defilement",
    "discharge",
    "disgorgement",
    "draff",
    "draggletail",
    "drainage",
    "dregs",
    "drool",
    "dry-rot",
    "dung",
    "dunghill",
    "dunghill",
    "earth-closet",
    "effusion",
    "eliminant",
    "emanation",
    "emission",
    "eructate",
    "evacuation",
    "excrement",
    "excreta",
    "excretion",
    "expectorate",
    "extravasation",
    "exudation",
    "feculence",
    "fetor",
    "filth",
    "foulings",
    "foulness",
    "garbage",
    "grime",
    "guano",
    "hog-wash",
    "immundity",
    "impurity",
    "infection",
    "keck",
    "leucorrhea",
    "maggots",
    "manure",
    "matter",
    "mildew",
    "mire",
    "mold",
    "mucidness",
    "muck",
    "mucor",
    "mud",
    "nastiness",
    "off-scum",
    "offal",
    "ordure",
    "paracentesis",
    "perspiration",
    "pollution",
    "purulence",
    "pus",
    "putrescence",
    "quagmire",
    "refuse",
    "rheum",
    "rot",
    "rubigo",
    "scurf",
    "secretion",
    "silt",
    "slabber",
    "slaver",
    "slime",
    "slobber",
    "slop",
    "slosh",
    "slubber",
    "sludge",
    "slush",
    "smudge",
    "smutch",
    "soiliness"
  ]

  ISN4 = [
    "accreting",
    "accruing",
    "aggrandizing",
    "aggravating",
    "ascending",
    "augmenting",
    "billowing",
    "biting",
    "breathing",
    "browsing",
    "budding",
    "cacating",
    "caressing",
    "cherishing",
    "chewing",
    "chomping",
    "clasping",
    "coddling",
    "coveting",
    "craving",
    "creating",
    "cuddling",
    "dandling",
    "dilating",
    "distending",
    "dottling",
    "draining",
    "dripping",
    "ejecting",
    "eliminating",
    "evacuating",
    "exhaling",
    "expanding",
    "expelling",
    "extending",
    "extravasating",
    "exuding",
    "fingering",
    "fondling",
    "foraging",
    "gnawing",
    "growing",
    "heaving",
    "imbedding",
    "infusing",
    "ingesting",
    "intumescing",
    "kissing",
    "licking",
    "littering",
    "masticating",
    "multiplying",
    "needing",
    "nestling",
    "nuzzling",
    "obtruding",
    "obtuding",
    "ogling",
    "oozing",
    "osculating",
    "patulating",
    "plucking",
    "plundering",
    "protruding",
    "puffing",
    "pugging",
    "puking",
    "pursing",
    "ravening",
    "regurgitating",
    "rejecting",
    "relishing",
    "requiring",
    "ruining",
    "savoring",
    "savoring",
    "secreting",
    "sipping",
    "smelling",
    "smothering",
    "sneezing",
    "spoiling",
    "stealing",
    "subjoining",
    "subsisting",
    "succoring",
    "sucking",
    "supping",
    "swigging",
    "swilling",
    "sheep-eyeing",
    "tasting",
    "tasting",
    "thieving",
    "tippling",
    "touching",
    "turgescing",
    "wanting",
    "waxing"
  ]

  ISN5 = [
    "anterior cavity",
    "anterior gland",
    "anterior hole",
    "anterior muscle",
    "anterior orifice",
    "anterior pores",
    "dirt cavity",
    "dirt hole",
    "dirt orifice",
    "dirt pores",
    "excreting cavity",
    "excreting gullet",
    "excreting holes",
    "excreting hollow",
    "excreting nooks",
    "excreting orifices",
    "excreting slot",
    "excreting void",
    "eye orifices",
    "eye pores",
    "eye voids",
    "navel orifice",
    "ooze cavity",
    "ooze gullet",
    "ooze hole",
    "ooze nooks",
    "ooze orifices",
    "ooze slot",
    "ooze void",
    "refuse cavity",
    "refuse gullet",
    "refuse hole",
    "refuse hollow",
    "refuse nooks",
    "refuse orifice",
    "refuse slot",
    "refuse spaces",
    "refuse void",
    "secret cavity",
    "secret gland",
    "secret hole",
    "secret muscle",
    "secret orifice",
    "secret pore",
    "secret slot",
    "secret void",
    "slime cavity",
    "slime gullet",
    "slime hole",
    "slime hollow",
    "slime muscle",
    "slime nooks",
    "slime openings",
    "slime orifices",
    "slime pores",
    "slime slot",
    "slime spaces",
    "slime void",
    "sweat cavities",
    "sweat cavity",
    "sweat gullet",
    "sweat hole",
    "sweat hollow",
    "sweat nooks",
    "sweat openings",
    "sweat orifices",
    "sweat pores",
    "sweat slot",
    "sweat spaces",
    "sweat void",
    "underarm cavity",
    "underarm gullet",
    "underarm hole",
    "underarm hollow",
    "underarm muscle",
    "underarm nooks",
    "underarm openings",
    "underarm orifices",
    "underarm pores",
    "underarm slot",
    "underarm spaces",
    "underarm void",
    "unmentionable cavity",
    "unmentionable gullet",
    "unmentionable hole",
    "unmentionable hollow",
    "unmentionable muscle",
    "unmentionable nook",
    "unmentionable openings",
    "unmentionable orifices",
    "unmentionable pores",
    "unmentionable slot",
    "unmentionable spaces",
    "unmentionable void",
    "wart cavity",
    "wart gullet",
    "wart holes",
    "wart hollows",
    "wart nooks"
  ]

  ISN6 = [
    "Bluthian",
    "Neranian",
    "Warterian",
    "Xanterian",
    "Bexian",
    "Cledugian",
    "Chugnetian",
    "Chyderian",
    "Dygian",
    "Danthian",
    "Deechnetian",
    "Eegrudgian",
    "Eichhornian",
    "Foognidian",
    "Fuhbagian",
    "Fidwoortian",
    "Fahdgian",
    "Feeshian",
    "Gharzan",
    "Gaazhogian",
    "Geeshworgian",
    "Gitchshidian",
    "Goopragian",
    "Gughokian",
    "Haagpokian",
    "Herwadian",
    "Hijkakian",
    "Hoolpodian",
    "Huquadian",
    "Jadtypian",
    "Jezchupian",
    "Jymptordian",
    "Kurkian",
    "Koodgian",
    "Lyxian",
    "Madrigian",
    "Nastian",
    "Abysmian",
    "Ickian",
    "Vomitian",
    "Putridgian",
    "Quensbian",
    "Tawgrian",
    "Perdian",
    "Tiliwidian",
    "Czerian",
    "Sizludian",
    "Kherbugian",
    "Quisnaglian",
    "Xertydigian",
    "Mudgrubbian",
    "Boogfudian",
    "Lilgoogian",
    "Luthdrungian",
    "Jugrudian",
    "Derrydinian",
    "Vudgnagian",
    "Vooptedgian",
    "Quooxmudgian",
    "Babbletogian",
    "Bugturgoorian",
    "Hogsodian",
    "Trufpatian",
    "Sowslinkian",
    "Crabkrudian",
    "Chartreudian",
    "Schnigerian",
    "Zitsneakian",
    "Cystrigian",
    "Crongian",
    "Kterigadian"
  ]

  ISN7 = [
    "Slizidge",
    "Burtidge",
    "Tisd",
    "Turt",
    "Bunt",
    "Burd",
    "Sacund",
    "Trund",
    "Crezd",
    "Hnot",
    "Jeck",
    "Kontluger",
    "Chitter",
    "Chunt",
    "Chooytop",
    "Chingdap",
    "Dyagenob",
    "Dugwart",
    "Pooper",
    "Ugly",
    "Abomination",
    "Fudwhomper",
    "Turtleg",
    "Waggletop",
    "Yaghord",
    "Marmwarb",
    "Yemzid",
    "Phutgrab",
    "Fetsmell",
    "Schaber",
    "Nerdnort",
    "Papperflabian",
    "Nudnuge",
    "Whiperbirt",
    "Sibbergrunt",
    "Saberdunt",
    "Thigwhip",
    "Whippinthig",
    "Zyzygdung",
    "Papchung",
    "Stinkbug",
    "Fardschid",
    "Yellowsnot",
    "Mucousdripper",
    "Purplebutt",
    "Hemorhonk",
    "Bladderpuff",
    "Hohogridge",
    "Klitbunkit",
    "Waxslimer",
    "Footfungus",
    "Floppydwart",
    "Danglidwid",
    "Slimepole",
    "Sillywalker",
    "Flat Toed Whump",
    "Clingbeetle",
    "Leecheater",
    "Maggotdangler",
    "Windpasser",
    "Fondlepiddle",
    "Crotchbug",
    "Toesmeller",
    "Slimemaggot",
    "Navelworm",
    "Earspider",
    "Noseleech",
    "Nostrilworm",
    "Wedgiewart",
    "Cankerlicker",
    "Pimple Popper"
  ]
  
  def generate
    ISN1[rand(ISN1.length)] + " the " +
    ISN2[rand(ISN2.length)] + " " +
    ISN3[rand(ISN3.length)] + " " +
    ISN4[rand(ISN4.length)] + " from the " +
    ISN5[rand(ISN5.length)] + " of a " +
    ISN6[rand(ISN6.length)] + " " +
    ISN7[rand(ISN7.length)]
  end
end
